/* Generated By:JavaCC: Do not edit this line. TestScriptConstants.java */
package tigase.test.parser;

public interface TestScriptConstants {

  int EOF = 0;
  int COMMENT = 4;
  int LONGDESCR = 6;
  int LETTER = 8;
  int DIGIT = 9;
  int STRING = 10;
  int DECIMAL = 11;
  int SIMPLESTR = 12;
  int VARNAME = 13;
  int PARAMNAME = 14;
  int COLON = 15;
  int SEMICOLON = 16;
  int AT = 17;
  int LBRACE = 18;
  int RBRACE = 19;
  int ONERROR = 20;
  int ASSIGN = 21;
  int PLUS = 22;
  int MINUS = 23;
  int STAR = 24;
  int SLASH = 25;

  int DEFAULT = 0;
  int IN_LONG_DESCR = 1;

  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<COMMENT>",
    "\">>\"",
    "\"<<\"",
    "<token of kind 7>",
    "<LETTER>",
    "<DIGIT>",
    "<STRING>",
    "<DECIMAL>",
    "<SIMPLESTR>",
    "<VARNAME>",
    "<PARAMNAME>",
    "\":\"",
    "\";\"",
    "\"@\"",
    "\"{\"",
    "\"}\"",
    "\"!!\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\" \"",
    "\"\\t\"",
    "\"?\"",
    "\"!\"",
    "\",\"",
  };

}
